### ISSUE TITLE
Multiple serializers fail

### ISSUE THREAD

**Issue by dfee** [asphalt-framework/asphalt-serialization#1]
Following the [documentation](http://asphalt-serialization.readthedocs.io/en/latest/configuration.html#multiple-serializers) and including this in the `component.components`:
```
    serialization:
      # backend: pickle
      serializers:
        json:
        pickle:
```

produces the following error:
```
ERROR 2017-05-09 00:03:54,352 [asphalt.core.runner:118][MainThread] Error during application startup
Traceback (most recent call last):
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/asphalt/core/runner.py", line 111, in run_application
    event_loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/Users/dfee/code/aio_chat/spark/component.py", line 29, in start
    await super().start(ctx)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/asphalt/core/component.py", line 107, in start
    self.add_component(alias)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/asphalt/core/component.py", line 96, in add_component
    component = component_types.create_object(type or alias, **config)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/asphalt/core/utils.py", line 167, in create_object
    return plugin_class(**constructor_kwargs)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/asphalt/serialization/component.py", line 44, in __init__
    assert check_argument_types()
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/typeguard.py", line 427, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/typeguard.py", line 396, in check_type
    check_union(argname, value, expected_type, memo)
  File "/Users/dfee/code/aio_chat/env/lib/python3.6/site-packages/typeguard.py", line 284, in check_union
    format(argname, typelist, qualified_name(value)))
TypeError: type of argument "serializers" must be one of (Dict, NoneType); got dict instead
```

**Comment by agronholm** [comment]
Does the following snippet produce the same error for you?
```python3
component = SerializationComponent(serializers={
    'json': {'encoder_options': {'allow_nan': False}},
    'msgpack': {'unpacker_options': {'encoding': 'iso-8859-1'}},
    'pickle': {'protocol': 3},
    'yaml': {'safe': False}
})```

**Comment by dfee** [comment]
Yes, it does. And, this configuration works, too:
```
    serialization:
      serializers:
        json: {}
        pickle: {}
```

This of course does not work:
```
SerializationComponent(serializers={'json': None})
```

So either it's a typo in the docs, or a bug in `SerializationComponent`'s type checking.

**Comment by agronholm** [comment]
This is indeed a bug in the type checking. See this:
```python
def __init__(self, serializers: Dict[str, Dict[str, Any]] = None, **default_serializer_args):
```
It expects keys of the "serializers" dicts to be dicts themselves; None is not allowed. Yet however the code does account for None as values. So I just need to fix the type annotation.
